HealthDataRepository/Models/ActivityMapping.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HealthDataRepository.Models
{
    public class ActivityMapping
    {
        [Key]
        [JsonIgnore]
        public virtual int Id { get; set; }

        [Required]
        public virtual string Source { get; set; }

        [Required]
        public virtual string MappingKey { get; set; }

        [Required]
        [JsonIgnore]
        public virtual int ActivityTypeId { get; set; }

    }
}

HealthDataRepository/Controllers/ActivityMappingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthDataRepository.Models;
using Microsoft.AspNetCore.Authorization;

namespace HealthDataRepository.Controllers
{
    [Authorize(AuthenticationSchemes = "oidc", Policy = "Administrator")]
    public class ActivityMappingsController : Controller
    {
        private readonly HealthDataRepositoryContext _context;

        public ActivityMappingsController(HealthDataRepositoryContext context)
        {
            _context = context;
        }

        // POST: ActivityMappings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Source,MappingKey,ActivityTypeId")] ActivityMapping activityMapping)
        {
            if (ModelState.IsValid)
            {

                activityMapping.Source = Enum.GetName(typeof(DataSource), Convert.ToInt32(activityMapping.Source));
                _context.Add(activityMapping);
                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", "ActivityTypes", new { Id = activityMapping.ActivityTypeId });
            }
            return View(activityMapping);
        }

        // GET: ActivityMappings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var activityMapping = await _context.ActivityMapping
               .FirstOrDefaultAsync(m => m.Id == id);
            if (activityMapping == null)
            {
                return NotFound();
            }
            return View(activityMapping);
        }
        // POST: ActivityMappings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activityMapping = await _context.ActivityMapping.FindAsync(id);
            _context.ActivityMapping.Remove(activityMapping);
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", "ActivityTypes", new { Id = activityMapping.ActivityTypeId });
        }


        private bool ActivityMappingExists(int id)
        {
            return _context.ActivityMapping.Any(e => e.Id == id);
        }
    }
}

HealthDataRepository/Views/ActivityMappings/Delete.cshtml
@model HealthDataRepository.Models.ActivityMapping

@{
    ViewData["Title"] = "Delete";
}


<div class="row">
    <div class="col-md-12 col-lg-6">
        <div class="card">
            <div class="card-header bg-danger text-white">
                <span class="card-title">Are you sure you want to delete Activity Mapping?</span>
            </div>

            <div class="card-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Source)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Source)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.MappingKey)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.MappingKey)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <a href="/ActivityTypes/Edit/@Model.ActivityTypeId" class="btn btn-info">Back to Activity Type</a>
                </form>
            </div>
        </div>
    </div>
</div>

HealthDataRepository/Views/ActivityMappings/_CreateForm.cshtml
@model HealthDataRepository.Models.ActivityMapping

    <form asp-controller="ActivityMappings" asp-action="Create">
        <input type="hidden" name="ActivityTypeId" value="@ViewData["ActivityTypeId"]" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Source" class="control-label"></label>
            <select asp-for="Source" asp-items="Html.GetEnumSelectList<DataSource>()" class="form-control"></select>
            <span asp-validation-for="Source" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MappingKey" class="control-label"></label>
            <input asp-for="MappingKey" class="form-control" />
            <span asp-validation-for="MappingKey" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}